### ISSUE TITLE
Video playback performance and accuracy varies greatly between video files

### ISSUE THREAD

**Issue by jpgill86** [NeuralEnsemble/ephyviewer#10]
I'm finding that for some of my video files, ephyviewer's VideoViewer works great and can play video at any speed pretty well. However, I also have video files for which this is not true at all. For these files, the video playback feature is broken in bizarre ways. I have speculations on why some of my files are different from others, but I am very uncertain.

My videos were captured using two different video capture software: QuickTime on Mac and Logitech Webcam Software on Windows. The MOV video files produced by QuickTime _sometimes_ play well in ephyviewer, but not always. I haven't yet found an MP4 video file produced by the Logitech Webcam Software that does play well with ephyviewer.

The symptoms are rather strange. You can try it for yourself using this example, which includes two video clips with different video codecs exported from a much longer video captured using the Logitech software in MP4 format:

https://files.mycloud.com/home.php?brand=webfiles&seuuid=89b32c3fb1da5c38c54dffd6b01334e8&name=ephyviewer-bad-video-playback-ex

You can change which of the two clips are loaded by changing one line in the Python script.

_For the MPEG4-encoded clip, and for the original H264-encoded video from which both examples were clipped (original not included in example):_

After pressing the play button, the video will play correctly for an interval of about 2 seconds before freezing on one frame. After a total of exactly 10 seconds have elapsed, the video will resume playing, jumping to the correct part of the video, but again it plays for only a 2 second interval. This pattern repeats every 10 seconds. The video resumes playback temporarily at times that are multiples of 10 seconds, even if playback was started in the middle of a decade (e.g., if the slider is dragged to t = 15 seconds before the play button is pressed, the video will remain on a frozen frame until time 20 seconds, at which point it will play for a short 2 second interval).

If the speed of playback is increased, this pattern does not seem to change at all. If the speed is decreased, the interval of successful playback may increase to perhaps 4 seconds (the amount seems to vary with the speed reduction factor and differs between the two computers I've tested this on), but there will still be a long period of no playback, and the cycle still repeats at multiples of 10 seconds.

_For the H264-encoded clip, but NOT for the original H264-encoded video:_

990 seconds of empty black frames are prepended to the video. Playback starts at t = 990 seconds. After that, an 8-second interruption pattern occurs, similar to the one described above. I did not create these clips starting from t = 990 seconds in the original video, so I have no idea where this number comes from.

I've also seen other amounts of time prepended to _unclipped_ videos originally captured as MOV files in QuickTime. For example, I have an MOV video that is about 30 minutes 25 seconds long. When I load it in ephyviewer, the slider has a total length of 3825 seconds, which is exactly 2000 seconds too long. The video doesn't start until exactly t = 2000 seconds; before that it is just black. When the slider is positioned sometime after 2000 seconds, the video can be played correctly, _but this time without the periodic interruption pattern I've described_. In cases like this where the interruption pattern is absent and the shift in start time is the only anomaly, I can work around the problem by introducing a corrective time shift:

    video_offset = -2000 # seconds
    video_source.t_starts[0] += video_offset
    video_source.t_stops[0]  += video_offset

However, this is of course not ideal. The extra time is moved to the end, and, besides, in most cases the interruption pattern is present.

I have hundreds of videos, so although I have dedicated many, many hours to trying to understand what's going on, I've only tested a handful of videos in that time! The symptoms might be even more varied than I'm reporting, and it's possible that the breakdown in playback performance has nothing to do with which video capture software I used.

However, it still seems reasonable to expect that video format/encoding has something to do with the problem. I have spent hours using two different video conversion programs trying to find a way to fix playback for my videos which are not playing well with ephyviewer, but I haven't found a solution yet. In fact, I wanted to include in my example an excerpt from a video which works perfectly for comparison, but the software I'm using to cut my multi-gigabyte file down to a 40 second clip induces the irregular playback issue in the exported file.

I am not very expert in video encoding formats, so I'm mostly guessing in the dark here (haha). I thought that perhaps this was an issue with PyAV's efficiency in playing certain compression formats, but then I noticed that both my original, uncut MOV and MP4 files -- some of which work flawlessly and others which do not -- use the same "Codec: H264 - MPEG-4 AVC (part 10) (avc1)" (according to VLC). Furthermore, of the two clips in my example, it's the one converted to "Codec: MPEG-4 Video (mp4v)" that actually works a little better. I'm not sure what actually makes some files work and others not. What's more, I'm not sure that odd behavior like the addition of hundreds of seconds of blank frames at the start of the video can be attributed solely to inefficient decoding algorithms!

If you can provide any insight into this problem, or if you know of a reliable format that works for you that I could convert my video files to, I would be incredibly grateful. ephyviewer is the perfect tool for the video and electrophys data analysis I want to do, and this video playback issue is the only thing holding me back right now!

**Comment by samuelgarcia** [comment]
This is anoying.

The video source is based on PyAV which itself is a wrapper on ffmpeg.

Seek in a video file is quite tricky even more if the video is compressed along time (not frame by frame)
The trick used in ephyviewer in datasource/video.FrameGrabber is based on this
https://github.com/mikeboers/PyAV/blob/master/examples/frame_seek_example.py

Maybe this cause the problem.

Maybe this is a problem of ffmpeg version itself. How did you install it. with conda ? Have you try diffrent OS ? ffmpeg versions ?

I will have a look tomorow. thank you for th example.

**Comment by samuelgarcia** [comment]
Just in case:  did you play with **video_times** in the MultiVideoFileSource ?

MultiVideoFileSource.video_filenames, video_times=None).
It is a vector of the True time of all frames from a avi file.
It is used internanly for seeking.
Because you cannot trust only the t_start for time alignement with signals if your recording is too long.
You need somehow to get the time vector of frames. Some camera offer a pulse at each grabbing.

**Comment by samuelgarcia** [comment]
Hi @jpgill86,
I made a patch for this problem on  my github #11.
Could you test ?

I change of strategy for videoviewer with an internal stack for frame request.

A major difficulty in the design of ephyviewer is that every data fetch (image, signal) is done in a separate thread so that the seek is smooth but if the fetch is too slow we have to drop frames or signal chunk when playing. But not the last one!! This ensure that when push stop we want a time alignement  for all viewers.

I also fixe the wrong automatique t_start/t_stop for navigation toolbar.
It was the case for the second files.

Note that you can be more agressive for the refresh time in the navigation toolbar with this **play_interval** (0.1 s by default):
```python
win = ephyviewer.MainViewer(debug = False, play_interval = 0.05)
```
Best

**Comment by samuelgarcia** [comment]
Oups. there are still some problems. Wait before testing.

**Comment by samuelgarcia** [comment]
I dig a bit about your problem in h264.
This format is an interframe compression. This mean that you have full frame every X second and frame in betwene are interpolated. Intuitive.

The engine for seeking in ephyveiwer is copy paste from PyAV example.
Video format do not all support absolut seeking. In h264, you can only seek to full frame. For in-between full frame seek you need to seek to the previous full frame and ask for next frame until you get the good one. This means that the farest from the last one the slowest it is.
In your file full frame are evry 10s so 300 frame.
So jumping to 0, 300, 600, 900 are super fast but jumping to 299, 599, 699 are super slow.
That is why in the previous implementation the image was frozen.

In the new patch,the image is not totally forzen but you get less and less FPS after 2seconds evry 10s.
You can try it. It is better than previous.

I will try to improve the situation with a small cache but it is more work.

**Comment by samuelgarcia** [comment]
I finally found a much simpler solution.

Try the latest comit on my repo and tell me if it is OK.

**Comment by jpgill86** [comment]
![not-worthy](https://user-images.githubusercontent.com/241234/43806667-e69d2a78-9a72-11e8-8fe5-91cac4d2d699.gif)

_**You are the best!**_

Your latest changes make all of my videos play smoothly! Some still have that odd starting-hundreds-of-seconds-late bug, but I can work around that by using the `video_offset` hack I mentioned above, or by using `MultiVideoFileSource`'s `video_times` parameter, as you suggested.

(And since I'd like to help track down the real cause of that problem, I'll look at it again when I have more time. If you're keen to investigate, my second example video, `feeding-aplysia-h264-encoding.mp4`, still has the start time of 990 seconds, even though your fixes did correct the navigation slider so that it starts at that time rather than 0.)

THANK YOU for spending your whole day working on this for me! I've been working in parallel, always several steps behind! I think your explanation is exactly right that the periodicity of the performance was a consequence of my video's full frames (key frames / I frames) being spaced 300 frames (10 seconds) apart. After you convinced me of that, I spent hours reading up on it and seeking methods for re-encoding my videos with more frequent key frames, haha. I was just about to give up when I show your most recent post here, and I am SO HAPPY that you found a better way!

You have made me VERY happy! This really is now the _perfect_ tool for what I work on! It was almost 2 years ago that I started working on a little tool for myself when I needed similar functionality for data review and couldn't find it elsewhere:

https://gist.github.com/jpgill86/d69e8a275bf4e112b44e7e1bf9920829

My solution resorted to rendering my data as a scrolling movie which I synced with my behavior videos by playing them in slave mode in VLC. The result looked like this:

https://drive.google.com/open?id=0Bwi4Db30eSd2WElPNmNIbEREV1E

It was a pretty good solution but had several drawbacks: (1) rendering the scrolling video took a long time, preventing me from reviewing data quickly; (2) the scrolling video took up extra hard drive space; (3) the scrolling video was not interactive, so if I decided I needed to change the scaling then I needed to re-render the video; (4) adding annotation (such as marking epochs) simply wasn't possible unless I was willing to re-render the video again and again as I worked.

I'm telling you all of this so that you understand how much I appreciate what you've built here and how grateful I am for it, and for your extra efforts to solve the problems I've encountered. THANK YOU THANK YOU THANK YOU. I will be singing your praises throughout the lab for a long time to come!

**Comment by samuelgarcia** [comment]
Thank you for the compliment.
Don't worry it was not the whole day : one hour at lab and one hour more when I get back home.
Furthermore I will soon need to read h264 files.
Real heros are Mike Boers (PyAV),  Luke Campagnola (pyqtgraph) and of course of QT and ffmpeg guys. ephyviewer is only an assemblage of al theses.

I am happy that you arr happy :)

I plan one day to make a stronger release of ehyviewer with clean, code, Ci and docs in a good english.
Maybe in 2019.
If you adopt the tools and like it, maybe you will be able to help me with the doc, code or review.

First I need to finish many things before:  neo, pyacq and tridesclous.

Have you tried pyacq ? it could interest you also. It is a distributed acquisition system for signal, video, event, spikes, ... It offer wrapper (with Node) to some devices and also offer some viewer very similar to ephyviewer but for (soft) real time monitoring.
The idea is quite the same as ephyviewer : you assemble many pieces to construct the soft you really need for experimental recording/monotoring.

For the second file, 990s is the real internal t_start of the mp4 file. Maybe because the software for exporting clip keep the old time scale, this make sens for video editing.

**Comment by samuelgarcia** [comment]
Close by #11

**Comment by jpgill86** [comment]
I'm happy to help improve ephyviewer. I'll be doing a lot of data analysis in the near future, so I expect to be working with it a lot. And I can certainly help with the documentation too. My English is pretty good. 😄

I have not tried pyacq or tridesclous yet, but I will certainly look into them. I've been dissatisfied with some aspects of my current data acquisition methods, so pyacq sounds very interesting. Can it capture video from a webcam and ephys data from a National Instruments DAQ with a common timestamp? I'm also likely to do some spike sorting in the very near future, so I'll look at tridesclous too.

Thanks again!
