### ISSUE TITLE
[TypeError: 'method' object is not connected] when I try to call TimeFreqViewer

### ISSUE THREAD

**Issue by flareno** [NeuralEnsemble/ephyviewer#124]
Hello,

First of all thanks for the great library you provide us!

I wrote a script to create my viewer where I visualize: raw traces, filtered traces and time frequency plots of the selected traces.
Months ago, when I actually wrote the script, it worked perfectly.
Today I reopen the script to show it to a new student of the lab and of course it crashes.

I use Spyder4 with Python 3.7 on Windows.
Epyviewer version 1.3.1

The relevant part of the script is the following:

```
sample_rate = 20000.
 t_start = 0.
 nb_channel = 16
  
 sigs= np.fromfile(raw_filename, dtype='float64').reshape(-1, nb_channel)
 sigs/= 1e6 # put in uV
 source_sig = InMemoryAnalogSignalSource(sigs, sample_rate, t_start)
 view3 = TimeFreqViewer(source=source_sig, name='tfr')
```
 
 When I run that last line I get the following error:

> Traceback (most recent call last):
> 
>   File "C:\Users\F.LARENO-FACCINI\Anaconda3\lib\site-packages\ephyviewer\timefreqviewer.py", line 313, in on_param_change
>     self.create_grid()
> 
>   File "C:\Users\F.LARENO-FACCINI\Anaconda3\lib\site-packages\ephyviewer\timefreqviewer.py", line 321, in create_grid
>     ViewBoxClass=MyViewBox,  vb_params={})
> 
>   File "C:\Users\F.LARENO-FACCINI\Anaconda3\lib\site-packages\ephyviewer\tools.py", line 58, in create_plot_grid
>     graphiclayout.clear()
> 
>   File "C:\Users\F.LARENO-FACCINI\Anaconda3\lib\site-packages\pyqtgraph\graphicsItems\GraphicsLayout.py", line 172, in clear
>     self.removeItem(i)
> 
>   File "C:\Users\F.LARENO-FACCINI\Anaconda3\lib\site-packages\pyqtgraph\graphicsItems\GraphicsLayout.py", line 165, in removeItem
>     item.geometryChanged.disconnect(self._updateItemBorder)
> 
> TypeError: 'method' object is not connected
 
I tried to research this type of error but I couldn't find any relevant information.
Thank you for any help you can give me!

Cheers,
Federica

**Comment by jpgill86** [comment]
Hi @flareno!

I am able to reproduce this using ephyviewer's example script `timefreq_viewer.py` with pyqtgraph 0.11.0 or later. With pyqtgraph 0.10.0, there is no error.

When running the script from the command line, the error is issued but the interface still launches and appears to work. When you run your script in Spyder, are you still able to use the app despite the error?

**Comment by jpgill86** [comment]
Hi @flareno,

I believe I fixed the issue. You can install the fix, now merged into the master branch, this way:

```
pip install -U git+https://github.com/NeuralEnsemble/ephyviewer 
```

I'd love to know if it works for you!

**Comment by flareno** [comment]
Hi @jpgill86!

The fix works perfectly, thank you so much!!

Have a good day,
Federica

**Comment by samuelgarcia** [comment]
Hi Jeffrey. thank you for having fixed that.
