### ISSUE TITLE
Scatter plot colors change randomly when moving points

### ISSUE THREAD

**Issue by jpgill86** [NeuralEnsemble/ephyviewer#132]
With pyqtgraph 0.11.1, animating a TraceViewer with scatter points results in this bizarre behavior (this example uses [trace_viewer_with_marker.py](https://github.com/NeuralEnsemble/ephyviewer/blob/master/examples/trace_viewer_with_marker.py)):

![randomly-changing-scatter-colors](https://user-images.githubusercontent.com/241234/104539686-09345700-55ec-11eb-8243-b9ad1a70abaf.gif)

The colors of points change randomly when the points are moved in any way. The colors should not change.

This buggy behavior was not present with pyqtgraph 0.11.0 and earlier.

I used `git bisect` on the pyqtgraph history and found the issue was introduced with pyqtgraph/pyqtgraph#1420, and more specifically the "Avoid unnecessary atlas rebuilds" commit (https://github.com/pyqtgraph/pyqtgraph/pull/1420/commits/38e4f678d98e63e5c8d1255a44824aed2ee441bc) that was later squashed when the PR was merged.

I'm not entirely confident in my diagnosis, but I think the problem involves pyqtgraph's [SymbolAtlas](https://github.com/pyqtgraph/pyqtgraph/blob/cd40562121b843a0da76bc407283f9967d4c2c4a/pyqtgraph/graphicsItems/ScatterPlotItem.py#L152) interacting poorly with [TraceViewer regenerating QBrushes with every redraw](https://github.com/NeuralEnsemble/ephyviewer/blob/b2e60a9d7a09967011b2ce9f1868dbdfacdf9d95/ephyviewer/traceviewer.py#L631) somehow. If I set ScatterPlotItem's [useCache](https://github.com/pyqtgraph/pyqtgraph/blob/cd40562121b843a0da76bc407283f9967d4c2c4a/pyqtgraph/graphicsItems/ScatterPlotItem.py#L392) option to `False`, the problem goes away, but naturally the plot becomes very slow if there are many points, so I don't want to do that.

I stumbled upon [this](https://github.com/pyqtgraph/pyqtgraph/issues/1020#issuecomment-745030021) and [this](https://github.com/LucaMarconato/dynamic_scatter_plot/pull/1), which address a different performance issue. On a hunch, I decided to try something similar in ephyviewer, and it seems to have solved the problem (#133). It simply involves caching the QBrushes before passing them off to pyqtgraph, so that they aren't destroyed with each redraw. I guess it preserves references to QBrushes that remain compatible with the SymbolAtlas cache indefinitely.

I think I will merge this fix into ephyviewer, but since I don't completely understand the underlying problem, I'm not sure whether to classify it as a bug fix for ephyviewer, or a workaround for a bug in pyqtgraph. The former seems more likely, but if it's the latter, I imagine the pyqtgraph people would want to know. @lidstrom83 and @j9ac9k, since you were both involved in pyqtgraph/pyqtgraph#1420, I'm tagging you here in case you have any interest in investigating further!

**Comment by j9ac9k** [comment]
Thanks for digging into this!  I'm in the middle of trying to get a few other PRs merged so I'll look into this more after that; @lidstorm83 if you have some time to investigate this, that would be appreciated.

**Comment by samuelgarcia** [comment]
Waoo!
Thank you for this complicated investigation.

**Comment by j9ac9k** [comment]
So annoyingly, I can't replicate this issue on macOS; I can tell from the original video that this was recorded on Windows, so I'll try and replicate there.  @jpgill86 do you happen to remember which Qt bindings/version you were using?

**Comment by jpgill86** [comment]
I was using PyQt5, and I'm pretty sure the version was 5.12.3.

**Comment by j9ac9k** [comment]
ok, still can't reproduce (haven't tried windows yet, but I will soon) but I have a pretty good idea as to why it is happening

**Comment by jpgill86** [comment]
If you want to try to reproduce the problem in Windows with conda, you can put this into a file named `environment.yml`:
```yaml
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pyqt=5.12.3
  - pyqtgraph=0.11.1
  - pip:
    - git+https://github.com/NeuralEnsemble/ephyviewer.git@b2e60a9  # just before my fix
```
and then run these commands:
```
conda env create -f environment.yml -n test
conda activate test
curl -o trace_viewer_with_marker.py https://raw.githubusercontent.com/NeuralEnsemble/ephyviewer/master/examples/trace_viewer_with_marker.py
python trace_viewer_with_marker.py
```

**Comment by j9ac9k** [comment]
oh, right; I probably installed the version w/ your fix 🤦
