### ISSUE TITLE
Automatic Color

### ISSUE THREAD

**Issue by tfoutz99** [NeuralEnsemble/ephyviewer#166]
Is there a way to call "on_automatic_color" in source code? I currently use:

```In [24]: view1.children()
Out[24]:
[<PyQt5.QtWidgets.QVBoxLayout at 0x7ffc90d92700>,
 <pyqtgraph.widgets.GraphicsView.GraphicsView at 0x7ffc90da3160>,
 <ephyviewer.traceviewer.TraceViewer_ParamController at 0x7ffc90da3430>,
 <PyQt5.QtCore.QThread at 0x7ffc802f29d0>]```

and then call:
```view1.children()[2].on_automatic_color()```

Is there a different way to call this? Thanks!

**Comment by samuelgarcia** [comment]
At the moment I don't think we have a clean API for auto color.

The way I do it is this one (which is more or less the same):

```python
n = ...# number of channel
viewer = ....
cmap = matplotlib.cm.get_cmap('jet' , n)
for i in range(n):
      color = [ int(e*255) for e in  matplotlib.colors.ColorConverter().to_rgb(cmap(i)) ]
      viewer.by_channel_params[f'ch{i}', 'color'] = color
```

This is somethign we could improve.

I keep this open, so.

**Comment by tfoutz99** [comment]
That works perfectly. Thanks!
<img width="1104" alt="Screen Shot 2021-09-27 at 11 14 14 AM" src="https://user-images.githubusercontent.com/68945/134936479-0320b344-f6e7-4ecc-a94f-815e3b745413.png">

**Comment by samuelgarcia** [comment]
Magnifique!
