### ISSUE TITLE
release ?

### ISSUE THREAD

**Issue by samuelgarcia** [NeuralEnsemble/ephyviewer#40]
Hi @jpgill86.
What do you think about a release soon of ephyviewer. You have done many improvement, we should release it.

Do you have any plane for orthyer improvement in June ?

I still want to fix icon integration and will do soon!!!!

**Comment by jpgill86** [comment]
I think this is a great idea. There are some small things I'd like to change/fix first, and I'd also like to revise the docs. Perhaps this doesn't need to be done for the release, but if you're OK with waiting a couple weeks I may be able to find the time.

I have another idea for adding additional icons. I'd love to have the new icon system in place so I can build on top of it!

**Comment by samuelgarcia** [comment]
No urgency.
I think we can wait for all what you want to add.
I will on holiday at the end of July, lets say a release before my holidays.
So I will be able to sip cokatail with relaxed mind.
Is it OK for you ?

**Comment by jpgill86** [comment]
Haha, sounds good. 🍸

**Comment by jpgill86** [comment]
We should work on this really soon since I guess you will be leaving in a week or two. I think I would like to just do a quick polish on the docs this weekend, and then I'll be happy to release. Sound reasonable?

**Comment by samuelgarcia** [comment]
Hi. This sounds good.

Le ven. 12 juil. 2019 16:59, Jeffrey Gill <notifications@github.com> a
écrit :

**Comment by jpgill86** [comment]
If you are happy with everything, I think we could create a release now!! Things to remember:

- [ ] Change `version.py`
- [ ] Update the release date in the release notes

**Comment by jpgill86** [comment]
Hmm, well I guess #63 should be fixed first...

**Comment by jpgill86** [comment]
#63 is fixed. I think we are again ready. 😋

**Comment by samuelgarcia** [comment]
I can do it if you want.
You have done evrything!!

**Comment by samuelgarcia** [comment]
Done!
Champagne!!

**Comment by samuelgarcia** [comment]
https://pypi.org/project/ephyviewer/#history

**Comment by jpgill86** [comment]
Hooray! Now you can sip your cocktail on holiday with a relaxed mind! 🥂

> I can do it if you want.

I think that because I don't have maintainer access to the PyPI project, you'll have to do these in the future! Unless you want to grant me maintainer access ([jpgill86](https://pypi.org/user/jpgill86/))... 😋

**Comment by samuelgarcia** [comment]
Of course.
You have been add to maintainer.
We could make an annoucement on neuralensemble mainling list if you want.

**Comment by jpgill86** [comment]
> You have been add to maintainer.

I promise to use my new powers only for good. 😈

> We could make an annoucement on neuralensemble mainling list if you want.

Sure! Do you want to do that? And if only this bug in elephant (NeuralEnsemble/elephant#236) would get fixed, I could finally announce my app too!
