### ISSUE TITLE
conda-forge recipe

### ISSUE THREAD

**Issue by jpgill86** [NeuralEnsemble/ephyviewer#81]
Hey @samuelgarcia, I'm thinking about creating a conda-forge recipe for ephyviewer. I haven't made one before, but it seems pretty easy. Do you have any objections?

**Comment by samuelgarcia** [comment]
Hi Jeffrey.
This is OK for me.
I don't use personally conda (too heavy) but many do.
I don't known if pyqtgraph is correctly installed with conda. Maybe you should check it.
I use to always install pyqtgraph with pip in conda but I don't remember why.


BTW : I presented ephyviewer to many people in my research center. I think many people was not aware of this tools and was quite happy to discover it.
Many should adopt it.
You were mentioned a lot. Thank to you I was able to argue that ephyviewer is truely an international project. héhé.

**Comment by jpgill86** [comment]
> This is OK for me.

Great, I'll look into it.

> I don't use personally conda (too heavy) but many do.

conda comes in two distributions: [Anaconda](https://www.anaconda.com/distribution/) and [Miniconda](https://docs.conda.io/en/latest/miniconda.html). I agree that Anaconda is much too heavy, but I find Miniconda to be very light. But if you're already using a Linux distribution with Python environment management tools, you may not need it. I'm running Windows, and conda is the easiest way to get PyAV for Windows as far as I know.

> I don't known if pyqtgraph is correctly installed with conda. Maybe you should check it. I use to always install pyqtgraph with pip in conda but I don't remember why.

I believe it [can be installed with conda](https://anaconda.org/search?q=pyqtgraph), but perhaps I should double check it.

>BTW : I presented ephyviewer to many people in my research center. I think many people was not aware of this tools and was quite happy to discover it. Many should adopt it. You were mentioned a lot. Thank to you I was able to argue that ephyviewer is truely an international project. héhé.

This makes me very happy! 🙌 First France, then USA, then the world... Be sure to [tell them about neurotic too](https://drive.google.com/file/d/12OxMmOEu3ojQgz5tsVHfcTkJnawSJZ7u/view), especially the ones afraid of programming! Once ephyviewer can be installed with conda, I plan next to get neurotic installable with conda.

**Comment by jpgill86** [comment]
Hi @samuelgarcia, I've got a conda-forge recipe ready to go here:

https://github.com/conda-forge/staged-recipes/pull/10103

I listed you as a co-maintainer. If that's alright with you, could you leave a comment in that pull request stating so?

**Comment by jpgill86** [comment]
ephyviewer is now on conda-forge!

https://anaconda.org/conda-forge/ephyviewer

It can be installed (along with Neo and PyAV, which are optional) using

```
conda create -n ephyviewer -c conda-forge python=3.7 ephyviewer python-neo av
```
